name: Docs
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs-material mkdocstrings-python
      - run: mkdocs gh-deploy --force
